configuration:
  swagger:
    app: 'Game Shop App'
    description: 'Game shop application built using Spring Boot'
    developer: 'Damir Zrnić'
    email: 'damir.zrnic@stu.ibu.edu.ba'

spring:
  data:
    mongodb:
      uri: mongodb+srv://damirzrnic:PopSmokeForTheNight@damircluster0.t4b9ywy.mongodb.net/?retryWrites=true&w=majority
      database: gameShopApp

security:
  jwt:
    secret: 'eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3MDE4NjkxNDUsImV4cCI6MTcwMTg3MDU4NX0.lRrISm5hYVLK8qLAXQK3aNCVKQu0_BcfYs-cvNKJBM'